# Generated by Django 4.2.13 on 2024-06-10 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de sesión exitoso'), ('LOGIN_FAILURE', 'Inicio de sesión fallido'), ('PASSWORD_CHANGE', 'Cambio de contraseña')], default='LOGIN_SUCCESS', max_length=100)),
            ],
            options={
                'db_table': 'session_log',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
    ]
